server {
    listen 8001;
    server_name lesesys.online www.lesesys.online;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name lesesys.online www.lesesys.online;

    ssl_certificate /etc/letsencrypt/live/lesesys.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lesesys.online/privkey.pem;

    location / {
        proxy_pass http://frontend:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Cookie $http_cookie;
    }
}